import {dbHealth} from '@/lib/db';
import {configuredProviders} from '@/lib/providers/config';

export async function GET(){
 const database=await dbHealth();
 const providers=configuredProviders();
 return Response.json({
  ok:true,
  app:'Edgeforce AI',
  version:'28.0.0',
  releaseCandidate:true,
  postReleaseOps:true,
  liveDataIntelligence:true,
  providerReconciliation:true,
  clvAnalytics:true,
  calibrationMap:true,
  rollingModelRankings:true,
  learnedModelWeights:true,
  decorrelatedModelCouncil:true,
  scenarioVolatilitySimulation:true,
  providerContextFusion:true,
  contextSourceAudit:true,
  strictFutureMarketWindow:true,
  sportOutcomeSimulation:true,
  teamScoreMonteCarlo:true,
  setMatchMonteCarlo:true,
  combatOutcomeMonteCarlo:true,
  playerStatMonteCarlo:true,
  playerProjectionContext:true,
  lineupAvailability:true,
  sameGameCorrelation:true,
  liveProbabilityBoard:true,
  predictionMarketAdapter:true,
  screenshotHistoryAnalytics:true,
  persistentWagerLedger:true,
  automaticSettlement:true,
  bankrollPerformanceAnalytics:true,
  anomalySignals:true,
  confidenceDecay:true,
  overUnderConfidenceDetection:true,
  sportEngines:19,
  historicalLearning:true,
  portfolioOptimizer:true,
  autonomousDecisionEngine:true,
  interactiveControlRoom:true,
  dataQualityGate:true,
  providerNormalization:true,
  providerFailover:true,
  providerCircuitBreaker:true,
  providerPayloadFreshnessGate:true,
  staleStoredOddsRejection:true,
  degradedModeDisclosure:true,
  securityHardening:true,
  productionSmokeTests:true,
  hostedPreviewGate:true,
  promotionWorkflow:true,
  rollbackWorkflow:true,
  configuredProviderCount:providers.length,
  database,
  time:new Date().toISOString()
 });
}
