import {dbHealth} from '@/lib/db';
import {configuredProviders} from '@/lib/providers/config';
import {RELEASE} from '@/lib/releaseManifest';

export const dynamic='force-dynamic';

export async function GET(){
 const started=Date.now();
 const database=await dbHealth();
 const providers=configuredProviders();
 return Response.json({
  ok:true,
  live:true,
  app:'Edgeforce AI',
  build:RELEASE.build,
  version:RELEASE.appVersion,
  modelVersion:RELEASE.modelVersion,
  migrationVersion:RELEASE.migrationVersion,
  releaseCandidate:true,
  productionHardened:true,
  readinessEndpoint:true,
  operationalHeartbeat:true,
  structuredObservability:true,
  providerReconciliation:true,
  providerCircuitBreaker:true,
  providerPayloadFreshnessGate:true,
  providerCertification:true,
  launchDoctor:true,
  staleStoredOddsRejection:true,
  degradedModeDisclosure:true,
  persistentWagerLedger:true,
  automaticSettlement:true,
  bankrollPerformanceAnalytics:true,
  walkForwardCalibration:true,
  controlledWeightPromotion:true,
  settledPredictionFeedback:true,
  calibratedModelSnapshots:true,
  automaticContextResimulation:true,
  contextChangeAudit:true,
  serverlessContextState:true,
  liveMarketRepricing:true,
  lineMovementTracking:true,
  steamDetection:true,
  automaticClosingLineCapture:true,
  signedClvTracking:true,
  actionableSteamAlerts:true,
  releaseIdentitySynchronized:true,
  distributionAwareSimulation:true,
  discreteLowScoreSimulation:true,
  simulationQuantiles:true,
  playerPropDistributionFamilies:true,
  eventLevelJointSimulation:true,
  learnedSgpCorrelation:true,
  gaussianCopulaJointEngine:true,
  sportMicroSimulation:true,
  plateAppearanceEngine:true,
  driveEngine:true,
  possessionEngine:true,
  shiftEngine:true,
  chanceEngine:true,
  pointGameSetEngine:true,
  granularSportEngines:7,
  multiProviderConsensusPricing:true,
  targetBookPricePreservation:true,
  robustPriceOutlierRejection:true,
  marketDispersionDetection:true,
  explicitSharpPublicBookRoles:true,
  priceShoppingIntelligence:true,
  regimeDetection:true,
  uncertaintyCalibration:true,
  dynamicConfidence:true,
  portfolioStressTesting:true,
  portfolioVarCvar:true,
  continuousDrawdownBrake:true,
  additiveExplainability:true,
  componentAblation:true,
  featureSensitivity:true,
  modelFragilityDiagnostics:true,
  liveReadOnlyWhatIf:true,
  batchDataContractAudit:true,
  durableAutomationHealth:true,
  productionCertification:true,
  staticReleaseAudit:true,
  mutationBodyLimit:true,
  hardenedContentSecurityPolicy:true,
  championChallengerGovernance:true,
  probabilityDriftDetection:true,
  automaticDriftWeightBrakes:true,
  nativeRealOddsIngestion:true,
  publicPredictionMarketFallback:true,
  runtimeNeonMigrationBootstrap:true,
  cloudflareRuntimeIdentity:true,
  cloudflareDeployPreflight:true,
  sportEngines:19,
  securityHardening:true,
  productionSmokeTests:true,
  hostedPreviewGate:true,
  promotionWorkflow:true,
  rollbackWorkflow:true,
  configuredProviderCount:providers.length,
  database,
  durationMs:Date.now()-started,
  time:new Date().toISOString()
 },{headers:{'Cache-Control':'no-store'}});
}
